# alpine based image with go installed
FROM golang:1.8.5-alpine3.6

EXPOSE 8080

COPY img/z.png /tmp/gopher.png
COPY server.go /tmp/server.go

RUN set -x \
        && go build -o /usr/local/demo-server /tmp/server.go

ENTRYPOINT ["/usr/local/demo-server"]

